$(document).ready(function (){
  $(".button-collapse").sideNav();
  $("select").material_select();
  $(".search").leanModal();
  $(".poems").leanModal({
    dismissible: false
  });
  $(".custom").leanModal();
  $('input.autocomplete').autocomplete({
    data: {
      "Adam Lindsay Gordon": null,
      "Alan Seeger": null,
      "Alexander Pope": null,
      "Algernon Charles Swinburne": null,
      "Ambrose Bierce": null,
      "Amy Levy": null,
      "Andrew Marvell": null,
      "Ann Taylor": null,
      "Anne Bradstreet": null,
      "Anne Bronte": null,
      "Anne Killigrew": null,
      "Anne Kingsmill Finch": null,
      "Annie Louisa Walker": null,
      "Arthur Hugh Clough": null,
      "Ben Jonson": null,
      "Charles Kingsley": null,
      "Charles Sorley": null,
      "Charlotte Bronte": null,
      "Charlotte Smith": null,
      "Christina Rossetti": null,
      "Christopher Marlowe": null,
      "Christopher Smart": null,
      "Coventry Patmore": null,
      "Edgar Allan Poe": null,
      "Edmund Spenser": null,
      "Edward Fitzgerald": null,
      "Edward Lear": null,
      "Edward Taylor": null,
      "Edward Thomas": null,
      "Eliza Cook": null,
      "Elizabeth Barrett Browning": null,
      "Emily Bronte": null,
      "Emily Dickinson": null,
      "Emma Lazarus": null,
      "Ernest Dowson": null,
      "Eugene Field": null,
      "Francis Thompson": null,
      "Geoffrey Chaucer": null,
      "George Eliot": null,
      "George Gordon, Lord Byron": null,
      "George Herbert": null,
      "George Meredith": null,
      "Gerard Manley Hopkins": null,
      "Helen Hunt Jackson": null,
      "Henry David Thoreau": null,
      "Henry Vaughan": null,
      "Henry Wadsworth Longfellow": null,
      "Hugh Henry Brackenridge": null,
      "Isaac Watts": null,
      "James Henry Leigh Hunt": null,
      "James Thomson": null,
      "James Whitcomb Riley": null,
      "Jane Austen": null,
      "Jane Taylor": null,
      "John Clare": null,
      "John Donne": null,
      "John Dryden": null,
      "John Greenleaf Whittier": null,
      "John Keats": null,
      "John McCrae": null,
      "John Milton": null,
      "John Trumbull": null,
      "John Wilmot": null,
      "Jonathan Swift": null,
      "Joseph Warton": null,
      "Joyce Kilmer": null,
      "Julia Ward Howe": null,
      "Jupiter Hammon": null,
      "Katherine Philips": null,
      "Lady Mary Chudleigh": null,
      "Lewis Carroll": null,
      "Lord Alfred Tennyson": null,
      "Louisa May Alcott": null,
      "Major Henry Livingston, Jr.": null,
      "Mark Twain": null,
      "Mary Elizabeth Coleridge": null,
      "Matthew Arnold": null,
      "Matthew Prior": null,
      "Michael Drayton": null,
      "Oliver Goldsmith": null,
      "Oliver Wendell Holmes": null,
      "Oscar Wilde": null,
      "Paul Laurence Dunbar": null,
      "Percy Bysshe Shelley": null,
      "Philip Freneau": null,
      "Phillis Wheatley": null,
      "Ralph Waldo Emerson": null,
      "Richard Crashaw": null,
      "Richard Lovelace": null,
      "Robert Browning": null,
      "Robert Burns": null,
      "Robert Herrick": null,
      "Robert Louis Stevenson": null,
      "Robert Southey": null,
      "Robinson": null,
      "Rupert Brooke": null,
      "Samuel Coleridge": null,
      "Samuel Johnson": null,
      "Sarah Flower Adams": null,
      "Sidney Lanier": null,
      "Sir John Suckling": null,
      "Sir Philip Sidney": null,
      "Sir Thomas Wyatt": null,
      "Sir Walter Raleigh": null,
      "Sir Walter Scott": null,
      "Stephen Crane": null,
      "Thomas Campbell": null,
      "Thomas Chatterton": null,
      "Thomas Flatman": null,
      "Thomas Gray": null,
      "Thomas Hood": null,
      "Thomas Moore": null,
      "Thomas Warton": null,
      "Walt Whitman": null,
      "Walter Savage Landor": null,
      "Wilfred Owen": null,
      "William Allingham": null,
      "William Barnes": null,
      "William Blake": null,
      "William Browne": null,
      "William Cowper": null,
      "William Cullen Bryant": null,
      "William Ernest Henley": null,
      "William Lisle Bowles": null,
      "William Morris": null,
      "William Shakespeare": null,
      "William Topaz McGonagall": null,
      "William Vaughn Moody": null,
      "William Wordsworth": null
    }
  });
});
